### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by CilginSinek** [codehasanali/mylinks#1]
`488-b16739db927c33d3.js:1 TypeError: Cannot read properties of undefined (reading 'toUpperCase')`

Lanyard sunucusunda değilsin sanırım o yüzden çöküyor tam [şuradan](https://github.com/codehasanali/mylinks/blob/main/src/app/page.tsx#L25)

**Comment by codehasanali** [comment]
hayır ! Discord  username değistirğim için çökuyor orası düzettcem sonra
